### PR TITLE
Exec tachikoma update 20150502150739

### PR DESCRIPTION
**Pull request by tachikomapocket**
:hamster::hamster::hamster: <br /> <br /> Strategy none
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6000284246909751476">Interval Pull Request as a Service - Tachikoma.io</a>

### CODE REVIEW

**Comment by cordoval** [comment]
this sounds like spam right @pborreli ?

**Comment by cordoval** [comment]
oh i see you are testing this service http://tachikoma.io/ he he

**Comment by cordoval** [comment]
hmm for a personal/commercial project i wouldn't use this though it looks like versioneye.com but more intrusive/automatic. In any case neat tool, just i believe in more responsibility tracking correctly the versions of dependencies. :+1:

**Comment by pborreli** [comment]
just testing it just create a PR anyway it's not a big deal of intrusion ..

**Pull request closed without merging**
